### ISSUE TITLE
'tshark' Error in running the preprocessing of pcaps

### ISSUE THREAD

**Issue by skumailraza** [Thijsvanede/FlowPrint#1]
_python -m flowprint --pcaps ../exec_clustering/pcaps_frompcaps_dataset --write flow.p_

_Reading ../exec_clustering/pcaps_frompcaps_dataset..._
_/home/kumailraza/FlowPrint/flowprint/reader.py:64: UserWarning: tshark exception: '[Errno 2] No such file or directory: 'tshark': 'tshark'', defaulting to pyshark_
  _.format(ex))_

_Output fingerprints:_

It does create the output file _flow.p_ but then the fingerprinting step gives an error.

**Comment by skumailraza** [comment]
installing tshark resolves this issue. Please add it to the dependencies in README.

**Comment by Thijsvanede** [comment]
Indeed, I recently added tshark as a backend because it is much faster. FlowPrint automatically tries to use the tshark backend and will default to pyshark if tshark cannot be found. This warning message indicates it default to pyshark because tshark is not installed. I have updated the README to include tshark as an optional dependency
