### ISSUE TITLE
Trouble preprocessing pcaps and generating fingerprints

### ISSUE THREAD

**Issue by skumailraza** [Thijsvanede/FlowPrint#2]
As per the README file of the repository, I'm trying to preprocess pcaps from Andrubis dataset to flows that FlowPrint can interpret but no matter what pcaps I use as input, the output fingerprints seem to be empty. Is there any specific input format for the pcaps to be used?

_python -m flowprint --pcaps c_dataset/ --write flows.p_

_Reading_ _c_dataset/..._
_/home/kumailraza/FlowPrint/flowprint/reader.py:64:_ UserWarning: tshark exception: '[Errno 2] No such file or directory: 'tshark': 'tshark'', defaulting to _pyshark_
  _.format(ex))_

_Output_ _fingerprints:_

flows.p:

�^Ccnumpy.core.multiarray
_reconstruct
q^@cnumpy
ndarray
q^AK^@�q^BC^Abq^C�q^DRq^E(K^AK^@�q^Fcnumpy
dtype
q^GX^B^@^@^@O8q^HK^@K^A�q       Rq
(K^CX^A^@^@^@|q^KNNNJ����J����K?tq^Lb�]q^Mtq^Nbh^@h^AK^@�q^Oh^C�q^PRq^Q(K$
�]q^Stq^Tb�q^U.

**Comment by Thijsvanede** [comment]
It looks like you are trying to read the directory `c_dataset/` instead of actual .pcap files, try using `c_dataset/*.pcap` to expand all pcap files in the given directory, or specify the entire path to the pcap file you want to parse, e.g. `c_dataset/example.pcap`

Please let me know if this works

I'll look for a way to throw an explicit error in the code if this happens

**Comment by Thijsvanede** [comment]
I have added warning messages both to the GitHub and pip versions of FlowPrint

**Comment by skumailraza** [comment]
c_dataset/*.pcap works, I found it already yes. Specifying the wildcard is necessary.
