### ISSUE TITLE
Can I save my model into files and load it from files to predict new unseen samples?

### ISSUE THREAD

**Issue by 3wh1te** [Thijsvanede/FlowPrint#7]
Add a feature to save model and load model.

**Comment by Thijsvanede** [comment]
As you have already closed this issue, I assume you found the functionality. For completeness: yes this is available in both the command line tool and the FlowPrint API:

**Command line tool**: 
First, you need to create flows from a `.pcap` file.
```python -m flowprint --pcaps <data.pcap> --write <flows.p>```
Next, you can store the fingerprints in a json file for later usage.
```python3 -m flowprint --read <flows.p> --fingerprint <fingerprints.json>```
Also see [https://flowprint.readthedocs.io/en/latest/usage/command_line.html](https://flowprint.readthedocs.io/en/latest/usage/command_line.html)

**FlowPrint API**
The `flowprint.FlowPrint` class provides `save` and `load` methods for this purpose.
Also see the API in [https://flowprint.readthedocs.io/en/latest/reference/flowprint.html#i-o-methods](https://flowprint.readthedocs.io/en/latest/reference/flowprint.html#i-o-methods)

If you have any further questions, please let me know.

**Comment by 3wh1te** [comment]
What I find is that the less my test data is, the worse result I will get. Because the fingerprint generated by little   test data is not bad. Is that right?

**Comment by Thijsvanede** [comment]
When creating a fingerprint with little data (a small number of flows), that fingerprint will have very few network destinations. This means it will become harder to correctly detect whether a fingerprint matches a know fingerprint.

To illustrate, suppose that we have known fingerprints with network destinations:

1. A B C D E F
2. A B G H

If we create a test fingerprint using network destinations A B we would find a closest match with fingerprint 2 (because this has a Jaccard similarity of 0.5 as opposed to a jaccard similarity of 0.33 for fingerprint 1). However, it might still actually be network activity from the same app as fingerprint 1. If we collect more data, we would perhaps generate fingerprint A B E instead, which would be more similar to fingerprint 1.

So the amount of data in both the training and testing fingerprint affect the accuracy of FlowPrint.

**Comment by 3wh1te** [comment]
I get it! thx！！！
