### ISSUE TITLE
There a question in FingerprintGenerator._fit_single_batch_

### ISSUE THREAD

**Issue by 3wh1te** [Thijsvanede/FlowPrint#9]
**Describe the question**
Every batch there will create a new cluster object and when I test my data, I need create a new cluster to recomputer the fingers.And the samples in cluster using the concatenate() func is useless, because self.samples always is zeros(0) in a new cluster object.
   ```
       # new cluster every time we call the _fit_single_batch_(), so when we use the samples, the samples must be zeros(0) 
        cluster = Cluster()
        # Cluster flows into network destinations
        cluster.fit(X, y)
```
```
       # Add X to samples, if before we use cluster.fit, we create a new cluster. There is no need to use concatenate()
        self.samples = np.concatenate((self.samples, X))
       # why not self.samples = X
```
**what i think**
I think cluster should be create as a member variable of the FingerprintGenerator. And it should be inited in \__init\__().And when I need to train my data, I need save fingerprints and cluster.  When I need to predict my data, I need load cluster ,too. 

Am i right? Or my comprehension of the method is wrong? Thx rely me!

**Comment by Thijsvanede** [comment]
Yes, what you are describing is in fact correct. Initially, this was how we implemented this method as well.

The reason for this concatenation is that we will likely soon have a student working on creating fingerprints from live network traffic. This means that we need to add new flows X to an existing cluster in real-time. We already started to experiment with this feature in the `Cluster.fit()` method, so that we can update the cluster using the fit method. Once this live-traffic feature is available, we will likely have a separate `fit()` and `update()` method for the Cluster.
